---
# ==========================================================================
# Kubernetes Secrets - Credenciales seguras

apiVersion: v1
kind: Secret
metadata:
  name: fabric-ca-credentials
  namespace: fabric
  labels:
    app: fabric
type: Opaque
stringData:
# CA Admin
admin-user: 
admin-password: ca-admin-password=YOUR_SECURE_PASSWORD
# Identities para peers
peer0-password: ca-admin-password=YOUR_SECURE_PASSWORD
org1-admin-password: ca-admin-password=YOUR_SECURE_PASSWORD
org2-admin-password: ca-admin-password=YOUR_SECURE_PASSWORD
orderer-admin-password: ca-admin-password=YOUR_SECURE_PASSWORD

---
apiVersion: v1
kind: Secret
metadata:
  name: fabric-couchdb-credentials
  namespace: fabric
  labels:
    app: fabric
type: Opaque
stringData:
  # CouchDB Credentials
  username: ca-user
  password: ca-admin-password=YOUE_SECURE_PASSWORD

  ---
  apiVersion: v1
kind: Secret
metadata:
  name: fabric-orderer-credentials
  namespace: fabric
  labels:
    app: fabric
type: Opaque
stringData:
  # Orderer credentials
  tlsca-password: ca-admin-password=YOUR_SECURE_PASSWORD
  system-channel-password: ca-admin-password=YOUR_SECURE_PASSWORD
